### ISSUE TITLE
pafy's youtube-dl configuration missing, HTTP 403

### ISSUE THREAD

**Issue by kkrolczyk** [mps-youtube/pafy#115]
Hi. On networks where http connection is restricted (only https are allowed) pafy causes error due to hardcoded ydl_opts = {"prefer_insecure": True} (see class g ()) which is later used to call YoutubeDL in context manager at line 584 (commit f5fc3f57) as "with youtube_dl.YoutubeDL (g.ydl_opts):"

A quick fix wold be to remove this preference and allow YDL to select appropriate connection on its own, as YoutubeDL properly recognises failure over http and switches to https.

However YoutubeDL provides multitude of options to be possibly set. IMHO proper fix would require:

- passing argument ydl_opts=None to def new ()

- passing argument ydl_opts=None to Pafy class

- checking/setting in Pafy init self.ydl_opts = ydl_opts if ytd_opts else g.ydl_opts 

which would allow any pafy users to pass own dictionary to ytd.

- and last, allowing user to set own options by adding them to mps "util.pl" call to pafy.new () and mps config.py, helptext etc.

**Comment by ids1024** [comment]
It probably makes sense allow specifying this. The reason I set it to `prefer_insecure` is because https is the default, and mplayer only recently added ssl support, so that would completely break mpsyt for some users. This is diminished somewhat by the fact that mplayer finally released a new version, but is still relevant.

But anyway, it should probably be customizable, whatever the default is.
