### ISSUE TITLE
low speed to get data on server

### ISSUE THREAD

**Issue by wdfsinap** [mps-youtube/pafy#123]
Hi, 

when I use pafy to get data from youtube on my server, it takes at least 4s, sometimes over 10s. but when I test it on my local computer, it only takes 0.9s. what's the problem?

there is the code:
#!/usr/bin/python
import pafy
import time

x = time.time()
id ='rLGFr8OF5Pc'
d = pafy.new("https://www.youtube.com/watch?v="+id)
print d
y = time.time()
z = y-x
print z

**Comment by ids1024** [comment]
This could be because of the time youtube-dl requires to load. Is it faster if you use version 0.3.76 (before youtube-dl was added as a dependency)?
https://github.com/mps-youtube/pafy/releases/tag/v0.3.76

Actually, that is not relevant if you are timing from after pafy has already been imported. But this is worth trying anyway.

**Comment by wdfsinap** [comment]
yes, when I use the version 0.376. It is quite fast. it takes only 0.25s to finish the program.
can you remove the youtube-dl module or modify it? because there is some bugs in the version 0.376

**Comment by wdfsinap** [comment]
like http://youtube.com/watch?v=Lhel0tzHE08 it get error:

line 339, in _extract_function_from_js
    args, body = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by ids1024** [comment]
The thing is, those bugs were fixed by adding youtube-dl as a dependency, which replaced some somewhat buggy code providing the same functionality as youtube-dl. Otherwise, bugfixes are currently being ported back to 0.3.x.

That specific (major) bug however has been fixed on the 0.3.x branch, and I will release a new a new 0.3.x version soon.

**Comment by ids1024** [comment]
Ok, I have released 0.3.78 fixing that bug: https://github.com/mps-youtube/pafy/releases/tag/v0.3.78

**Comment by wdfsinap** [comment]
thanks. this version looks good.
